use crate::data::MissionDefinition;

/// Generate a complete, production-ready Rust source file from a mission definition.
pub fn generate_rust(mission: &MissionDefinition) -> String {
    let mut out = String::with_capacity(4096);

    push_header(&mut out, mission);
    push_states(&mut out, mission);
    push_bit_fields(&mut out, mission);
    push_actions(&mut out, mission);
    push_layout_comment(&mut out, mission);
    out
}

fn push_header(out: &mut String, mission: &MissionDefinition) {
    out.push_str(&format!(
        "// ============================================================\n\
         // GOAP Mission: {}\n\
         // Mission Type : {}\n\
         // Variant: {}\n\
         // Generated by GOAP Mission Designer\n\
         // ============================================================\n\n\
         use crate::models::atomics::{{Action, WorldState, GoalState}};\n\n",
        mission.name, mission.mission_type, mission.variant
    ));
}

fn push_bit_fields(out: &mut String, mission: &MissionDefinition) {
    out.push_str(
        "// ============================================================\n\
         // BIT FIELD CONSTANTS\n\
         // ============================================================\n\n"
    );

    for field in mission.sorted_fields() {
        let name = &field.name.to_uppercase();

        let mask_name  = format!("{}_MASK",  name);
        let shift_name = format!("{}_SHIFT", name);

        out.push_str(&format!(
            "// {} : {}-bit field  bits {}-{}\n\
             pub const {:31} : u64 = 0x{:016X};\n\
             pub const {:31} : u64 = 0x{:016X};\n",
            field.name, field.bit_width, field.bit_offset, field.end_bit(),
            mask_name,  field.mask(),
            shift_name, field.bit_offset,
        ));

        for (i, name) in field.value_names.iter().enumerate() {
            let val = (i as u64) << field.bit_offset;
            out.push_str(&format!(
                "pub const {name_upper:32}: u64 = 0x{val:016X};\n",
                name_upper = format!("{}_{}", field.name, name),
                val = val,
            ));
        }
        out.push('\n');
    }
}

fn push_actions(out: &mut String, mission: &MissionDefinition) {
    out.push_str(&format!(
        "// ============================================================\n\
         // ACTIONS  ({} total)\n\
         // ============================================================\n\n\
         pub const ACTIONS : [Action; {}] = [\n",
        mission.actions.len(), mission.actions.len()
    ));

    for action in &mission.actions {
        if !action.description.is_empty() {
            out.push_str(&format!("    // {}\n", action.description));
        }

        out.push_str(&format!(
            "    Action {{\n\
                     name                    : \"{}\",\n\
                     pre_mask                : 0x{:08X},\n\
                     pre_value               : 0x{:08X},\n\
                     effect_mask             : 0x{:08X},\n\
                     effect_value            : 0x{:08X},\n\
                     cost                    : {}\n\
                 }},\n",
            action.name,
            action.pre_mask,
            action.pre_value,
            action.effect_mask,
            action.effect_value,
            action.cost,
        ));
    }
    out.push_str("];\n\n");
}

fn push_states(out: &mut String, mission: &MissionDefinition) {
    out.push_str(&format!(
        "// ============================================================\n\
         // MISSION STATES\n\
         // ============================================================\n\n\
         /// Initial world state\n\
         pub const INITIAL_STATE : WorldState = WorldState(0x{:016X});\n\n\
         /// Goal state\n\
         pub const GOAL_STATE  : GoalState  = GoalState (0x{:016X});\n\n",
        mission.initial_state,
        mission.goal_state,
    ));
}

fn push_layout_comment(out: &mut String, mission: &MissionDefinition) {
    let bar = "─".repeat(68);
    out.push_str(&format!("/*\n┌{bar}┐\n"));
    out.push_str(&format!("│  BIT LAYOUT  ({} bits used of 64 available)\n", mission.bits_used()));
    out.push_str(&format!("├{bar}┤\n"));

    for field in mission.sorted_fields() {
        let values_preview: Vec<&str> = field.value_names.iter().take(4).map(String::as_str).collect();
        let preview = if field.value_names.len() > 4 {
            format!("{}, ...", values_preview.join(", "))
        } else {
            values_preview.join(", ")
        };
        out.push_str(&format!(
            "│  Bits {:2}-{:2} : {:12} ({:1} bit{})  [{}]\n",
            field.bit_offset, field.end_bit(),
            field.name, field.bit_width,
            if field.bit_width == 1 { " " } else { "s" },
            preview,
        ));
    }

    out.push_str(&format!("└{bar}┘\n*/\n"));
}